---
title: "notatka z zajęć 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}

install.packages("tidyverse")

library(tidyverse)

```


```{r}
?mpg
```


```{r}


ggplot(data = mpg) +
  geom_point(aes(x = cty, 
                 y = hwy,
                 color = manufacturer,
                 alpha = year,
                 size = displ)) +
  geom_smooth()

```

```{r}
ggplot(data = mpg, aes(x = cty, 
                 y = hwy)) +
  geom_point(aes(color = manufacturer,
                 alpha = year,
                 size = displ)) +
  geom_smooth()
```

```{r}
ggplot(data = mpg, aes(x = cty, 
                 y = hwy)) + 
  geom_smooth() +
  geom_point(aes(color = manufacturer)) +
  geom_rug() +
  geom_text(aes(label = year)) +
  coord_polar()
 
```



```{r}
ggplot(map_data("world",
                region = 'Russia'), 
        aes(long, lat, 
            group = group)) +
  geom_polygon(fill = "white", 
               color = "black") 
  
```


```{r}

ggplot(map_data("world",
                region = 'Poland'), 
        aes(long, lat, 
            group = group)) +
  geom_polygon(fill = "white", 
               color = "black") +
  

```

```{r}
ggplot(mpg, aes(x = cty, 
                 y = hwy)) + 
  geom_smooth() +
  geom_point(aes(color = manufacturer)) +
  facet_wrap(~class)

```


```{r}

ggplot(mpg, aes(x = cty, 
                 y = hwy)) + 
  geom_smooth() +
  geom_point(aes(color = manufacturer)) +
  facet_grid(year~class)


```




```{r}



```




```{r}
ggplot(panteon) +
  geom_bar(aes(x = gender,
               fill = gender)) +
  facet_wrap(~continentName)
```

