---
title: "zaj 2 grupa 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tidyverse")

library(tidyverse)
```


```{r}

ggplot(mpg, aes(x = hwy, y = cty)) +
  geom_point(aes(size = cyl,
                 color = factor(cyl))) +
  geom_smooth() +
  scale_color_manual(values = c(1, 34, 89, 651)) +
  labs(title = "Spalanie na autostradzie i w mieście",
       subtitle = "najoszczędniejsze samochody mają cztery cylindry",
       caption = "Źródło: Panteon 1.0",
       x = "oszczędnosć na autostradzie",
       y = "oszczędność w mieście") +
  theme_minimal()

```


```{r}

library(ggthemes)

```


```{r}
ggplot(mpg, aes(x = hwy, y = cty)) +
  geom_point(aes(size = cyl,
                 color = factor(cyl))) +
  geom_smooth() +
  scale_color_manual(values = c(1, 34, 89, 651)) +
  labs(title = "Spalanie na autostradzie i w mieście",
       subtitle = "najoszczędniejsze samochody mają cztery cylindry",
       caption = "Źródło: Panteon 1.0",
       x = "oszczędnosć na autostradzie",
       y = "oszczędność w mieście") +
  theme_minimal()
```



```{r}


ggplot(mpg, aes(x = hwy, 
                y = cty)) +
  geom_jitter() +
  geom_smooth() +
  geom_rug() +
  facet_wrap(~year)

```

```{r}

ggplot(mpg, aes(x = hwy, 
                y = cty)) +
  geom_jitter() +
  geom_smooth() +
  geom_rug() +
  facet_grid(cyl~year)


```

```{r}

ggplot(mpg, aes(x = hwy, 
                y = cty)) +
  geom_jitter() +
  geom_smooth() +
  geom_rug() +
  facet_grid(cyl~year) +
  coord_polar()

```



```{r}
ggplot(map_data("world",
                region = 'Russia'),
        aes(long, lat,
            group = group)) +
  geom_polygon(fill = "white",
               color = "black")
```


```{r}

ggplot(map_data("world",
                region = 'Poland'),
        aes(long, lat,
            group = group)) +
  geom_polygon(fill = "red",
               color = "black") +
  coord_quickmap()

```


```{r}
table(mpg$manufacturer)
```

```{r}
panteon2 <- read_csv("https://raw.githubusercontent.com/Tomasz-Olczyk/wizualizacjaR/main/podstawy/panteon_s.csv")
```














```{r}
ggplot(panteon) +
  geom_bar(aes(x = gender,
               fill = gender)) +
  facet_wrap(~continentName)
```



```{r}
ggplot(panteon) + 
  geom_bar(mapping = aes(x = gender, color = gender)) + 
  facet_wrap(~continentName)

```

```{r cars}
summary(cars)
```

```{r}

```

