---
title: "Raport parametryzowany pokazujący parametry L_star i HPI dla płci `r params$płeć` z `r params$kraj` urodzeni po `r params$od`"
author: "Tomasz Olczyk"
date: "`r Sys.Date()`"
output: html_document
params: 
  kod:
    value: FALSE
  płeć:
    value: Male
    choices: [Male, Female]
  kraj:
    value: POL
  od:
    value: 1900
    input: slider
    min: 1000
    max: 2000
    sep: ""
  
    
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$kod)
```

```{r}
library(tidyverse)
```

```{r}

panteon <- read_csv("https://raw.githubusercontent.com/Tomasz-Olczyk/wizualizacjaR/main/podstawy/panteon_s.csv")

```

```{r}

panteon %>%
  filter(gender == params$płeć,
         countryCode3 == params$kraj,
         birthyear > params$od) %>%
  ggplot() +
  geom_point(aes(x = HPI, y = L_star)) +
  labs( title = paste("parametry L_star i HPI dla płci", params$płeć,
                      "z ", params$kraj))

```

teekst [@burns1992]

bibliografia
