---
title: "Parametry L_star o HPI dla `r params$płeć`, z `r params$kraj` urodzonych po `r params$od`"
author: "Tomasz Olczyk"
date: "`r Sys.time()`"
output: html_document
params:
  płeć:
    value: Male
    choices: [Female, Male]
  kraj:
    value: USA
  od:
    value: 1900
    input: slider
    min: 1000
    max: 2000
    sep: ""
  do:
    value: 1900
    input: slider
    min: 1000
    max: 2000
    sep: ""
  printcode: TRUE
  messages: TRUE
bibliography: references.bib
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = params$printcode,
                      message = params$messages)
```

Dzisiaj jest: `r Sys.Date()`

```{r}
library(tidyverse)
```

```{r }
panteon <- read_csv('https://raw.githubusercontent.com/Tomasz-Olczyk/wizualizacjaR/main/podstawy/panteon_s.csv')
```

```{r}
panteon %>%
  filter(gender ==  params$płeć,
         countryCode3 == params$kraj,
         birthyear > params$od,
         birthyear < params$do) %>%
  ggplot() +
  geom_point(aes(x = L_star, y = HPI)) +
  labs(title = paste("Parametry L_star o HPI dla osób", params$płeć, "z", params$kraj,"urodzene między", params$od, "a", params$do))
```

[@kassambara2013]

Bibliografia
