---
title: "Paski klimatu"
output: html_document
editor_options: 
  chunk_output_type: console
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
```

```{r}
klimat <- read_csv("/Users/golemxiv/Downloads/v3.mean_GISS_homogenized/step2.v3.csv")
```

Lizbona za Dominikiem Roye

```{r}
library(lubridate)
library(RColorBrewer)


```


```{r}

#import the annual temperatures
temp_lisboa <- read_csv("temp_lisboa.csv")

str(temp_lisboa)

```

```{r}
#select only the annual temperature and year column
temp_lisboa_yr <- select(temp_lisboa, YEAR, metANN)

#rename the temperature column
temp_lisboa_yr <- rename(temp_lisboa_yr, ta = metANN)

#missing values 999.9
summary(temp_lisboa_yr) 
```

```{r}
temp_lisboa_yr <- mutate(temp_lisboa_yr, ta = ifelse(ta == 999.9, NA, ta))
```


```{r}
temp_lisboa_yr <- mutate(temp_lisboa_yr, 
                         date = str_c(YEAR, "01-01", sep = "-") %>% ymd())
```


Ustawimy motyw

```{r}
theme_strip <- theme_minimal()+
                 theme(axis.text.y = element_blank(),
                       axis.line.y = element_blank(),
                       axis.title = element_blank(),
                       panel.grid.major = element_blank(),
                       legend.title = element_blank(),
                       axis.text.x = element_text(vjust = 3),
                       panel.grid.minor = element_blank(),
                        plot.title = element_text(size = 14, face = "bold")
                       )


col_strip <- brewer.pal(11, "RdBu")
```



```{r}
ggplot(temp_lisboa_yr,
             aes(x = date, y = 1, fill = ta))+
        geom_tile()+
           scale_x_date(date_breaks = "6 years",
                     date_labels = "%Y",
                     expand = c(0, 0))+
           scale_y_continuous(expand = c(0, 0))+
           scale_fill_gradientn(colors = rev(col_strip))+
             guides(fill = guide_colorbar(barwidth = 1))+
            labs(title = "LISBOA 1880-2018",
                caption = "Datos: GISS Surface Temperature Analysis")+
              theme_strip
```


### Średnie temperatury roczne zmiany w stacji na Okęcie


```{r}
okęcie <- read_csv("okęcie.csv")
```

```{r}
#select only the annual temperature and year column
temp_okęcie_r <- select(okęcie, YEAR, metANN, `D-J-F`)

#rename the temperature column
temp_okęcie_r <- rename(temp_okęcie_r, ta = metANN, td = `D-J-F`)

#missing values 999.9
summary(temp_okęcie_r) 
```


```{r}
temp_okęcie_r <- mutate(temp_okęcie_r, ta = ifelse(ta == 999.9, NA, ta),
                        temp_okęcie_r, td = ifelse(td == 999.9, NA, td))
```


```{r}
temp_okęcie_r <- mutate(temp_okęcie_r, 
                         date = str_c(YEAR, "01-01", sep = "-") %>% ymd())
```




```{r}
ggplot(temp_okęcie_r,
             aes(x = date, y = 1, fill = ta))+
        geom_tile()+
           scale_x_date(date_breaks = "6 years",
                     date_labels = "%Y",
                     expand = c(0, 0))+
           scale_y_continuous(expand = c(0, 0))+
           scale_fill_gradientn(colors = rev(col_strip))+
             guides(fill = guide_colorbar(barwidth = 1))+
            labs(title = "Warszawa 1880-2024",
                caption = "źródło: GISS Surface Temperature Analysis") +
              theme_strip
```



### Zmiana średniej temperatury w Warszawia

```{r}
ggplot(temp_okęcie_r,
             aes(x = date, y = 1, fill = td))+
        geom_tile()+
           scale_x_date(date_breaks = "6 years",
                     date_labels = "%Y",
                     expand = c(0, 0))+
           scale_y_continuous(expand = c(0, 0))+
           #scale_fill_gradientn(colors = rev(col_strip))+
   scale_fill_stepsn(colors=c("#08306B", "white", "#67000D"),
                    values = rescale(c(min(temp_okęcie_r$td, na.rm = TRUE), 0, max(temp_okęcie_r$td, na.rm = TRUE))),
                    n.breaks = 12) +
             guides(fill = guide_colorbar(barwidth = 1))+
            labs(title = "Warszawa 1880-2024",
                caption = "źródło: GISS Surface Temperature Analysis") +
              theme_strip
```

### Zmiana średniej temperatury globalnej


```{r}

library(scales)
library(glue)

```


```{r}

t_data <- read_csv("glbtemp.csv", skip = 1, na = "***") %>%
 select(year = Year, t_diff = `J-D`) %>%
  drop_na()


```


```{r}

t_data %>%
  ggplot(aes(x = year, y = 1, fill = t_diff)) +
  geom_tile(show.legend = FALSE) +
  scale_fill_stepsn(colors=c("#08306B", "white", "#67000D"),
                    values = rescale(c(min(t_data$t_diff), 0, max(t_data$t_diff))),
                    n.breaks = 12) +
  coord_cartesian(expand=FALSE) +
  scale_x_continuous(breaks=seq(1890, 2020, 30)) +
  labs(title= glue("Global temperature change ({min(t_data$year)}-{max(t_data$year)})")) +
  theme_void() +
  theme(
    axis.text.x = element_text(color="white",
                               margin =margin(t=5, b=10, unit="pt")),
    plot.title = element_text(color="white",
                               margin =margin(b=5, t=10, unit="pt"),
                              hjust= 0.05),
    plot.background = element_rect(fill="black")
)

ggsave("warming_stripes.png", width=8, height=4.5)


```

