---
title: "voronoi circular"
author: "Tomasz Olczyk"
date: "6/6/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(devtools)
install_github("garretrc/ggvoronoi")
```


```{r}
library(ggvoronoi)
```

```{r}
set.seed(45056)
x <- sample(1:200,100)
y <- sample(1:200,100)
points <- data.frame(x, y,
                     distance = sqrt((x-100)^2 + (y-100)^2))
circle <- data.frame(x = 100*(1+cos(seq(0, 2*pi, length.out = 2500))),
                     y = 100*(1+sin(seq(0, 2*pi, length.out = 2500))),
                     group = rep(1,2500))

ggplot(points) +
    geom_voronoi(aes(x=x,y=y,fill=distance))

ggplot(points) +
    geom_voronoi(aes(x=x,y=y,fill=distance),outline=circle)

ggplot(points) +
    geom_voronoi(aes(x=x,y=y,fill=distance),fill=NA,color="black")
```


```{r}
library(ggvoronoi)
library(ggplot2)

# Circle
s <- seq(0, 2 * pi, length.out = 3000)
circle <- data.frame(x = 120 * (1 + cos(s)),
                     y = 120 * (1 + sin(s)),
                     group = rep(1, 3000))

ggplot(df, aes(x, y, fill = dist)) +
  geom_voronoi(outline = circle,
               color = 1, size = 0.1) +
  scale_fill_gradient(low = "#B9DDF1",
                      high = "#2A5783",
                      guide = FALSE) +
  theme_void() +
  coord_fixed()
```

