---
title: "nieudane animacje z panteonem"
author: "Tomasz Olczyk"
date: "3/20/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Spróbujemy skonstruować animację ostatnich pięciu wieków lat pozycji Państw jeśli chodzi o liczbę osób sławnych ich sumaryczne HPI i sumaryczne LPstar


```{r}
Panteon_VC <- panteon %>%
  filter(birthyear >= 1800) %>%
  group_by(birthyear, 
            countryCode3) %>%
  summarise(sławy = row_number(),
            hpi = cumsum(HPI),
            L_Star = cumsum(L_star))
```


Z wykorzystaniem mutate i cumsum

```{r}

Panteon_VC_3 <- panteon %>%
  filter(birthyear >= 1800) %>%
  group_by(birthyear, 
            countryCode3,
           continentName) %>%
  summarise(hpi = sum(HPI),
            L_Star = sum(L_star)) %>%
  group_by(countryCode3) %>%
  mutate(hpi = cumsum(hpi),
         L_Star = cumsum(L_Star)) %>%
  ungroup()
```


```{r}

Panteon_VC_2 <- panteon %>%
  filter(birthyear >= 1800) %>%
  group_by(birthyear, 
            countryCode3, 
           continentName) %>%
  summarise(count = n()) %>%
  group_by(countryCode3) %>%
  mutate(count = cumsum(count)) %>%
  ungroup()

```



Panteon podsumowania z kumulatywnymi danymi


```{r}
Panteon_VC_2 <- panteon %>%
  filter(birthyear >= 1800, birthyear < 1990) %>%
  group_by(birthyear, 
            countryCode3, 
           continentName) %>%
  summarise(count = n(),
            hpi = sum(HPI),
            lstar = sum(L_star)) %>%
  group_by(countryCode3) %>%
  mutate(sławy = cumsum(count),
         kumulatywne_hpi = cumsum(hpi),
        kumulatywne_lstar = cumsum(lstar)) %>%
  ungroup()
```





```{r}

pp <- ggplot(Panteon_VC_2, aes(x= kumulatywne_hpi, 
                             y = kumulatywne_lstar,
                             color = continentName)) +
  geom_point(aes(size = sławy,
                 frame = birthyear,
                 ids = countryCode3))  
  
```


```{r}
pp

```

```{r}

ggplotly(pp)

```

Tylko kontynenty


```{r}

kontynenty <- panteon %>%
  filter(birthyear >= 1800, birthyear < 1980) %>%
  group_by(birthyear, 
           continentName) %>%
  summarise(count = n(),
            hpi = sum(HPI),
            lstar = sum(L_star)) %>%
  group_by(continentName) %>%
  mutate(sławy = cumsum(count),
         kumulatywne_hpi = cumsum(hpi),
        kumulatywne_lstar = cumsum(lstar)) %>%
  ungroup()
```


```{r}

wykres_kontynenty <- ggplot(kontynenty, aes(x= kumulatywne_hpi, 
                             y = kumulatywne_lstar,
                             color = continentName)) +
  geom_point(aes(size = sławy,
                 frame = birthyear,
                 ids = continentName))  
  
```


```{r}
ggplot(kontynenty, aes(x= kumulatywne_hpi, 
                             y = kumulatywne_lstar,
                             color = continentName)) +
  geom_point(aes(size = sławy))  +
  labs(title = 'rok: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(birthyear) 
```



```{r}
wykres_kontynenty
```



```{r}

ggplotly(wykres_kontynenty)

```
